import ReduxProvider from "@/store/provider";
import "./globals.css";
import Header from "./ui/header/header";
import Footer from "./ui/footer";

export const metadata = {
  title: "Lavish Whim",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        <ReduxProvider>
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
